<?php
session_start(); require_once '../../config/db.php';
if (empty($_SESSION['student_id'])) { header('Location: login.php'); exit; }
$eventId=(int)($_GET['eventId']??0); $type=($_GET['type']??'')==='antispoof'?'antispoof':'presence';
$event=$eventId?$conn->query("SELECT EventId,EventName FROM event WHERE EventId=$eventId LIMIT 1")->fetch_assoc():null;
if(!$event){header('Location: profile-dashboard.php');exit;}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $type==='antispoof'?'Anti-spoofing challenge':'Presence check' ?> | NAAP</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;padding:20px;box-sizing:border-box;background:#0b1220;color:#e5edf8;font:15px Inter,Arial,sans-serif}.card{max-width:510px;width:100%;background:#17233b;border:1px solid #31415d;border-radius:22px;padding:28px;box-sizing:border-box;text-align:center}.tag{display:inline-block;color:#7dd3fc;background:#0c4a6e55;border-radius:20px;padding:6px 11px;font-size:12px;font-weight:800;text-transform:uppercase}h1{margin:15px 0 8px;font-size:24px}p{color:#b8c5d9;line-height:1.5}.camera{display:none;width:100%;max-height:290px;object-fit:cover;transform:scaleX(-1);border-radius:16px;background:#020617;margin:18px 0}.challenge{margin:18px 0;padding:16px;border-radius:14px;background:#0f172a;color:#fff;font-weight:800;font-size:17px}.btn{width:100%;padding:13px;border:0;border-radius:12px;background:#2563eb;color:#fff;font-weight:800;font-size:15px;cursor:pointer}.btn:disabled{opacity:.55;cursor:not-allowed}.muted{font-size:13px}</style></head><body><main class="card"><span class="tag"><?= $type==='antispoof'?'Anti-spoofing challenge':'Presence check' ?></span><h1><?= htmlspecialchars($event['EventName']) ?></h1><p><?= $type==='antispoof'?'Allow camera access and complete the live challenge to verify that you are present.':'Confirm that you are actively attending this event.' ?></p><video id="camera" class="camera" autoplay muted playsinline></video><div id="challenge" class="challenge">Preparing your challenge...</div><button id="complete" class="btn" disabled><?= $type==='antispoof'?'Verifying automatically...':'Complete verification' ?></button><p id="message" class="muted" aria-live="polite"></p></main><script src="../../assets/js/lib/face-api.min.js"></script><script>
const type=<?=json_encode($type)?>,eventId=<?=$eventId?>,button=document.getElementById('complete'),message=document.getElementById('message'),video=document.getElementById('camera');let selected,stream,poll,hold,submitting=false;const challenges=[{id:'LEFT',text:'Turn your head slowly to the left, then back to center.'},{id:'RIGHT',text:'Turn your head slowly to the right, then back to center.'},{id:'BLINK',text:'Blink twice while looking at the camera.'}];
async function submit(){if(submitting)return;submitting=true;button.disabled=true;message.textContent='Submitting verification...';const fd=new FormData();fd.append('event_id',eventId);fd.append('check_type',type);try{const r=await fetch('../../config/API/endpoints/index.php?action=complete_verification',{method:'POST',body:fd}),d=await r.json();if(!d.success)throw Error(d.message);message.textContent='Verified. Returning to your Student Portal...';if(stream)stream.getTracks().forEach(t=>t.stop());setTimeout(()=>location.href='profile-dashboard.php',900)}catch(e){message.textContent=e.message||'Unable to submit verification.';submitting=false;if(type==='presence')button.disabled=false}}
function passed(l){const p=l.positions,n=p[30],a=p[36],b=p[45],yaw=(n.x-(a.x+b.x)/2)/Math.max(1,Math.abs(b.x-a.x));if(selected.id==='LEFT')return yaw<-.12;if(selected.id==='RIGHT')return yaw>.12;const le=Math.abs(p[38].y-p[40].y)/Math.max(1,Math.abs(p[36].x-p[39].x)),re=Math.abs(p[43].y-p[47].y)/Math.max(1,Math.abs(p[42].x-p[45].x));return le<.22||re<.22}
async function scan(){if(submitting||video.readyState<2)return;try{const face=await faceapi.detectSingleFace(video,new faceapi.TinyFaceDetectorOptions({inputSize:256,scoreThreshold:.55})).withFaceLandmarks();if(!face){message.textContent='No face detected. Center your face in the camera.';clearTimeout(hold);hold=null;return}if(passed(face.landmarks)){message.textContent='Challenge detected — verifying automatically...';if(!hold)hold=setTimeout(submit,700)}else{message.textContent='Face detected. Perform the displayed challenge.';clearTimeout(hold);hold=null}}catch(_){}}
async function start(){if(type==='presence'){document.getElementById('challenge').textContent='Tap the button below to confirm your presence.';button.disabled=false;return}selected=challenges[Math.floor(Math.random()*challenges.length)];document.getElementById('challenge').textContent=selected.text;message.textContent='Loading secure face detection...';try{await Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri('../../assets/models'),faceapi.nets.faceLandmark68Net.loadFromUri('../../assets/models')]);stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});video.srcObject=stream;video.style.display='block';await new Promise(ok=>video.onloadedmetadata=ok);await video.play();message.textContent='Face detection active. Complete the challenge to continue automatically.';poll=setInterval(scan,160)}catch(_){message.textContent='Camera access and face detection are required. Check permission, then reload this page.';button.textContent='Camera required'}}button.addEventListener('click',()=>{if(type==='presence')submit()});start();
</script></body></html>
